# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Tests

on:
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2.3.0

      - name: Resolve Swift Package Dependencies
        run: swift package resolve

      - name: Build & Test
        run: swift test --enable-test-discovery
